globalThis.AngkorSites=(()=>{
 let context,data,pending,revision=0,leafletGroup;
 const periods=['隋唐','五代十国','宋辽金西夏','元','明'],cityPeriods=['宋辽金西夏','元','明'];
 const controls={'隋唐':'ancientCapitalTangWalls','五代十国':'ancientCapitalSouthernTangWalls','宋辽金西夏':'ancientCapitalLiaoJinWalls','元':'ancientCapitalYuanWalls','明':'ancientCapitalMingQingWalls'};
 const categories={walls:{zh:'城墙／城门'},temples:{zh:'寺庙／宫殿'},platforms:{zh:'平台'},water:{zh:'水系'}};
 const detailLayers=['angkor-city-fill','angkor-fill','angkor-lines','angkor-efeo-lines','angkor-labels'],capitalLayers=['angkor-capital-point','angkor-capital-label'],layers=[...detailLayers,...capitalLayers];
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const en=()=>context.language()==='en',overlays=()=>context.state().mapOverlays;
 const active=ps=>ps.find(p=>overlays().ancientCapitalPeriods?.[p]!==false);
 async function load(){if(data)return;pending||=Promise.all(['osm','efeo','surroundings'].map(n=>fetch('data/angkor/'+n+'.geojson?v=2').then(r=>{if(!r.ok)throw Error(r.status);return r.json();}))).then(ds=>{if(ds.some(d=>d.type!=='FeatureCollection'))throw Error('Invalid Angkor data');data=ds.flatMap(d=>d.features);}).finally(()=>pending=null);await pending;}
 function collection(){return {type:'FeatureCollection',features:overlays().chinaAncientCapitals&&overlays().ancientCapitalWalls?(data||[]).flatMap(f=>{const ps=f.properties.role==='city-extent'?cityPeriods:[f.properties.period||'宋辽金西夏'],p=ps.find(p=>overlays().ancientCapitalPeriods?.[p]!==false&&overlays()[controls[p]]!==false);return p?[{...f,properties:{...f.properties,period:p,color:f.properties.category==='water'?'#2f92b8':HistoricalPeriods.colors[p],displayName:en()?(f.properties.nameEn||f.properties.name):f.properties.name}}]:[];}):[]};}
 function capital(){const period=active(['宋辽金西夏','元','明','隋唐','五代十国']);return {type:'FeatureCollection',features:overlays().chinaAncientCapitals&&period?[{type:'Feature',geometry:{type:'Point',coordinates:[103.8589,13.4413]},properties:{id:'angkor-capital',name:'吴哥城',nameEn:'Angkor Thom',displayName:en()?'Angkor Thom':'吴哥城',category:'walls',period,color:HistoricalPeriods.colors[period],origin:'osm',sourceUrl:'https://www.openstreetmap.org/way/1221842998',sourceTitle:'吴哥城现状范围',license:'ODbL',licenseUrl:'https://www.openstreetmap.org/copyright',referenceUrl:'https://apsaraauthority.gov.kh/temples/',note:'高棉帝国吴哥地区古都参照；现存吴哥城主体形成于12世纪末，周边包含9—15世纪遗迹。按同期年代使用现有朝代筛选，不表示中国王朝统治。'}}]:[]};}
 function labelData(d){return {type:'FeatureCollection',features:d.features.filter(f=>f.properties.label&&f.properties.role!=='city-extent').map(f=>({type:'Feature',properties:f.properties,geometry:{type:'Point',coordinates:f.properties.labelCoordinates}}))};}
 function html(p){return '<b>'+esc(en()?(p.nameEn||p.name):p.name)+'</b><p>'+esc(categories[p.category]?.zh)+' · '+esc(p.historicalEra||'高棉帝国·吴哥时期')+(p.dateText?' · '+esc(p.dateText):'')+'</p><p>'+esc(p.note)+'</p><a href="'+esc(p.sourceUrl)+'" target="_blank" rel="noopener">'+esc(p.sourceTitle)+' ↗</a><br><a href="'+esc(p.licenseUrl)+'" target="_blank" rel="noopener">'+(p.origin==='osm'?'© OpenStreetMap contributors · ':'© Archives EFEO · ')+esc(p.license)+' ↗</a><br><a href="'+esc(p.referenceUrl||'https://archives.efeo.fr/index.php/fca-2-dg-2756')+'" target="_blank" rel="noopener">历史资料 ↗</a>';}
 async function sync(map,group){const token=++revision;leafletGroup?.remove();leafletGroup=null;if(!overlays().chinaAncientCapitals){if(map)for(const id of layers)if(map.getLayer(id))map.setLayoutProperty(id,'visibility','none');return;}
  try{await load();if(token!==revision)return;const d=collection(),labels=labelData(d),c=capital();if(map){
   for(const [id,features] of [['angkor-sites',d],['angkor-site-labels',labels],['angkor-capital',c]]){if(map.getSource(id))map.getSource(id).setData(features);else map.addSource(id,{type:'geojson',data:features,...(id==='angkor-sites'?{attribution:'© OpenStreetMap contributors · ODbL | Archives EFEO · CC BY-NC-SA 4.0'}:{})});}
   const before=map.getStyle().layers.find(l=>l.type==='symbol')?.id;
   if(!map.getLayer(detailLayers[0]))map.addLayer({id:detailLayers[0],type:'fill',source:'angkor-sites',minzoom:12,filter:['==',['get','role'],'city-extent'],paint:{'fill-color':['get','color'],'fill-opacity':.12}},before);
   if(!map.getLayer(detailLayers[1]))map.addLayer({id:detailLayers[1],type:'fill',source:'angkor-sites',minzoom:12,filter:['all',['==',['geometry-type'],'Polygon'],['!=',['get','role'],'city-extent']],paint:{'fill-color':['get','color'],'fill-opacity':['case',['==',['get','origin'],'efeo'],.025,['==',['get','category'],'water'],.18,.14]}},before);
   if(!map.getLayer(detailLayers[2]))map.addLayer({id:detailLayers[2],type:'line',source:'angkor-sites',minzoom:12,filter:['==',['get','origin'],'osm'],paint:{'line-color':['get','color'],'line-width':['case',['==',['get','role'],'city-extent'],1.7,1.15]}},before);
   if(!map.getLayer(detailLayers[3]))map.addLayer({id:detailLayers[3],type:'line',source:'angkor-sites',minzoom:12,filter:['==',['get','origin'],'efeo'],paint:{'line-color':['get','color'],'line-width':1.4,'line-dasharray':[4,3]}},before);
   if(!map.getLayer(detailLayers[4]))map.addLayer({id:detailLayers[4],type:'symbol',source:'angkor-site-labels',minzoom:13,layout:{'text-field':['get','displayName'],'text-font':['Open Sans Regular','Arial Unicode MS Regular'],'text-size':12,'text-justify':'center','text-anchor':'center','text-max-width':12,'text-padding':5},paint:{'text-color':['get','color'],'text-halo-color':'white','text-halo-width':1.4}},before);
   for(const period of periods){const id='angkor-capital-'+period;if(!map.hasImage(id))map.addImage(id,HistoricalPeriods.capitalImage(HistoricalPeriods.colors[period]),{pixelRatio:2});}
   if(!map.getLayer(capitalLayers[0]))map.addLayer({id:capitalLayers[0],type:'symbol',source:'angkor-capital',minzoom:0,layout:{'icon-image':['concat','angkor-capital-',['get','period']],'icon-size':.9,'icon-allow-overlap':true}});
   if(!map.getLayer(capitalLayers[1]))map.addLayer({id:capitalLayers[1],type:'symbol',source:'angkor-capital',minzoom:0,layout:{'text-field':['get','displayName'],'text-font':['Open Sans Regular','Arial Unicode MS Regular'],'text-size':12,'text-anchor':'top','text-offset':[0,1.2],'text-allow-overlap':true},paint:{'text-color':['get','color'],'text-halo-color':'white','text-halo-width':1.5}});
   for(const id of layers)map.setLayoutProperty(id,'visibility','visible');context.front?.();
  }else if(group){leafletGroup=L.layerGroup().addTo(group);const z=context.zoom?.()||13;if(z>=12)L.geoJSON(d,{style:f=>({color:f.properties.color,weight:1.4,dashArray:f.properties.origin==='efeo'?'6 4':undefined,fill:/Polygon$/.test(f.geometry.type),fillOpacity:f.properties.role==='city-extent'?.12:.14}),onEachFeature:(f,l)=>{l.bindPopup(()=>html(f.properties));if(z>=13&&f.properties.label&&f.properties.role!=='city-extent')l.bindTooltip(esc(f.properties.displayName),{permanent:true,direction:'center',className:'angkor-site-label'});}}).addTo(leafletGroup);for(const f of c.features){const p=f.geometry.coordinates;L.marker([p[1],p[0]],{icon:L.divIcon({html:HistoricalPeriods.capitalSvg(f.properties.color),className:'angkor-capital-icon',iconSize:[20,20]})}).bindTooltip(esc(f.properties.displayName),{permanent:true,direction:'bottom'}).bindPopup(()=>html(f.properties)).addTo(leafletGroup);}}
  }catch(error){console.warn('Angkor sites',error);context.error?.();}
 }
 function click(map,event){if(!overlays().chinaAncientCapitals)return false;const available=layers.filter(id=>map.getLayer(id));if(!available.length)return false;const p=event.point,hits=map.queryRenderedFeatures([[p.x-5,p.y-5],[p.x+5,p.y+5]],{layers:available});const f=hits.find(f=>f.properties.role!=='city-extent')||hits[0];if(!f)return false;new maplibregl.Popup().setLngLat(event.lngLat).setHTML(html(f.properties)).addTo(map);return true;}
 return {init:c=>context=c,sync,click,collection,capital,categories};
})();
