const ClassicalSites=(()=>{
 let context,data,catalog,pending,leafletGroup;
 const layers=['classical-sites-fill','classical-sites-line','classical-sites-points','classical-sites-labels','classical-sites-names','classical-sites-standalone-points','classical-sites-inferred-lines'],signatures=new WeakMap();
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const en=()=>context.language()==='en',overlays=()=>context.state().mapOverlays;
 const wallControls={'夏商':'ancientCapitalShangWalls','周':'ancientCapitalZhouWalls','秦汉':'ancientCapitalQinHanWalls','魏晋南北朝':'ancientCapitalHanWeiWalls','隋唐':'ancientCapitalTangWalls','宋辽金西夏':'ancientCapitalLiaoJinWalls','元':'ancientCapitalYuanWalls','明':'ancientCapitalMingQingWalls','清':'ancientCapitalMingQingWalls'};
 function enabled(){const o=overlays();return Boolean(o.chinaAncientCapitals&&o.ancientCapitalWalls);}
 async function load(){if(data&&catalog)return;pending||=Promise.all(['data/classical-sites/sites.geojson?v=7','data/classical-sites/catalog.json?v=7'].map(u=>fetch(u).then(r=>{if(!r.ok)throw Error(r.status);return r.json();}))).then(([d,c])=>{data=d;catalog=c;}).finally(()=>pending=null);await pending;}
 function collection(){const o=overlays();return {type:'FeatureCollection',features:enabled()?(data?.features||[]).filter(f=>wallControls[f.properties.period]&&o[wallControls[f.properties.period]]!==false).map(f=>({...f,properties:{...f.properties,displayName:en()?f.properties.enName:f.properties.name,color:['natural','water'].includes(f.properties.role)?'#277caa':HistoricalPeriods.colors[f.properties.period]||'#bd9200'}})):[]};}
 function position(f){if(f.properties.labelCoordinates)return f.properties.labelCoordinates;const geom=f.geometry;if(geom.type==='Point')return geom.coordinates;let ring=geom.type==='Polygon'?geom.coordinates[0]:geom.type==='MultiPolygon'?geom.coordinates[0][0]:geom.coordinates;if(geom.type==='LineString')return ring[Math.floor(ring.length/2)];ring=ring.slice(0,-1);return ring.reduce((s,p)=>[s[0]+p[0]/ring.length,s[1]+p[1]/ring.length],[0,0]);}
 function siteFeatures(){const d=collection(),keys=new Set(d.features.map(f=>f.properties.siteKey));return {type:'FeatureCollection',features:(catalog?.sites||[]).filter(s=>keys.has(s.key)).map(s=>{const visible=d.features.filter(f=>f.properties.siteKey===s.key),period=visible.some(f=>f.properties.period===s.period)?s.period:visible[0].properties.period;return {type:'Feature',geometry:{type:'Point',coordinates:s.center},properties:{siteKey:s.key,name:s.name,enName:s.enName,displayName:en()?s.enName:s.name,period,periodLabel:s.periodLabel,heritageId:s.heritageId||'',tentative:s.tentative,color:HistoricalPeriods.colors[period]||'#bd9200'}};})};}
 function html(p){const s=catalog?.sites.find(s=>s.key===p.siteKey),name=en()?p.enName:p.name,siteName=en()?s?.enName:s?.name;
 const related=(data?.features||[]).filter(f=>f.properties.siteKey===p.siteKey&&f.properties.label!==false&&(f.properties.role!=='area'||f.properties.boundaryLabel));
 return '<b>'+esc(name)+'</b><p>'+esc(siteName)+' · '+esc(p.periodLabel||s?.periodLabel)+'</p><p>'+esc(p.note||(en()?'Public archaeological geometry; distinct from a surveyed ancient city boundary.':'城墙、遗址区和建筑分别标注；公开标绘不等于某一期完整城界。'))+'</p><p>'+esc(s?.tentative?(en()?'UNESCO Tentative List, not an inscribed World Heritage property.':'世界遗产预备名单，尚非正式世界遗产。'):(en()?'Related World Heritage property: ':'关联世界遗产：')+(s?.heritageId||''))+'</p>'+
 (s?.checklistItem?'<p><button type="button" class="popup-action" data-checklist-map="worldHeritage" data-item="'+esc(s.checklistItem)+'">'+(context.isVisited?.(s.checklistItem)?(en()?'Unmark visited':'取消打卡'):(en()?'Mark visited':'标记已去'))+'</button></p>':'')+'<p><button type="button" class="popup-action" data-classical-focus="'+esc(p.siteKey)+'">'+(en()?'Show site':'定位遗址')+'</button></p><details><summary>'+(en()?'Main remains':'主要遗迹')+' ('+related.length+')</summary>'+related.map(f=>'<button type="button" class="popup-action" data-classical-focus="'+esc(f.properties.id)+'">'+esc(en()?f.properties.enName:f.properties.name)+'</button> ').join('')+'</details><small>'+esc(p.attribution||'© OpenStreetMap contributors · ODbL')+'</small><br>'+(p.sourceUrl?'<a href="'+esc(p.sourceUrl)+'" target="_blank" rel="noopener">'+(en()?'Geometry source':'矢量来源')+' ↗</a><br>':'')+'<a href="'+esc(s?.referenceUrl||p.referenceUrl)+'" target="_blank" rel="noopener">'+(en()?'Site information':'遗址资料')+' ↗</a>';}
 async function focus(id){await load();const s=catalog.sites.find(s=>s.key===id),f=data.features.find(f=>f.properties.id===id),key=s?.key||f?.properties.siteKey;if(!key)return;const o=overlays();o.chinaAncientCapitals=true;o.ancientCapitalWalls=true;for(const f of data.features.filter(f=>f.properties.siteKey===key)){const control=wallControls[f.properties.period];if(control)o[control]=true;}context.changed?.();context.focus?.(s?s.center:position(f),s?14:17);}
 async function sync(map,group){if(!context)return;if(leafletGroup){leafletGroup.remove();leafletGroup=null;}if(!enabled()){if(map){for(const id of layers)if(map.getLayer(id))map.setLayoutProperty(id,'visibility','none');signatures.delete(map);}return;}
 try{await load();if(!enabled())return;const d=collection(),labels={type:'FeatureCollection',features:d.features.filter(f=>f.properties.label!==false&&(f.properties.role!=='area'||f.properties.boundaryLabel)).map(f=>({...f,properties:{...f.properties,pointFeature:f.geometry.type==='Point'},geometry:{type:'Point',coordinates:position(f)}}))},names=siteFeatures();names.features=names.features.filter(f=>!context.mergedMarkerVisible?.(f.properties.siteKey));
 if(map){const sig=JSON.stringify([en(),...Object.values(wallControls).map(k=>overlays()[k]!==false),names.features.map(f=>f.properties.siteKey)]);if(signatures.get(map)===sig&&map.getSource('classical-sites'))return;
 for(const [id,value] of [['classical-sites',d],['classical-sites-labels',labels],['classical-sites-names',names]]){if(map.getSource(id))map.getSource(id).setData(value);else map.addSource(id,{type:'geojson',data:value});}
 const before=map.getStyle().layers.find(l=>l.type==='symbol')?.id,paintColor=['get','color'];const specs=[
 {id:layers[0],type:'fill',source:'classical-sites',minzoom:11,filter:['in',['geometry-type'],['literal',['Polygon','MultiPolygon']]],paint:{'fill-color':paintColor,'fill-opacity':['case',['==',['get','role'],'area'],.08,['==',['get','role'],'natural'],.10,.18]}},
 {id:layers[1],type:'line',source:'classical-sites',minzoom:11,filter:['all',['!=',['geometry-type'],'Point'],['!=',['get','inferredBoundary'],true]],paint:{'line-color':paintColor,'line-width':['case',['==',['get','role'],'wall'],1.8,1.2]}},
 {id:layers[2],type:'circle',source:'classical-sites',minzoom:14,filter:['==',['geometry-type'],'Point'],paint:{'circle-radius':3.5,'circle-color':paintColor,'circle-stroke-color':'white','circle-stroke-width':1}},
 {id:layers[3],type:'symbol',source:'classical-sites-labels',minzoom:15,layout:{'text-field':['get','displayName'],'text-font':['Open Sans Regular','Arial Unicode MS Regular'],'text-size':12,'text-max-width':12,'text-anchor':['case',['==',['get','pointFeature'],true],'top','center'],'text-offset':['case',['==',['get','pointFeature'],true],['literal',[0,.8]],['literal',[0,0]]],'text-justify':'center','text-padding':5},paint:{'text-color':paintColor,'text-halo-color':'white','text-halo-width':1.5}},
 {id:layers[4],type:'symbol',source:'classical-sites-names',minzoom:0,maxzoom:15,layout:{'text-field':['get','displayName'],'text-font':['Open Sans Regular','Arial Unicode MS Regular'],'text-size':13,'text-anchor':'top','text-offset':[0,1],'text-padding':5},paint:{'text-color':paintColor,'text-halo-color':'white','text-halo-width':1.5}},
 {id:layers[5],type:'circle',source:'classical-sites-names',maxzoom:15,paint:{'circle-radius':4,'circle-color':paintColor,'circle-stroke-color':'white','circle-stroke-width':1}},
 {id:layers[6],type:'line',source:'classical-sites',minzoom:11,filter:['==',['get','inferredBoundary'],true],paint:{'line-color':paintColor,'line-width':1.5,'line-dasharray':[4,3]}}
 ];for(const spec of specs){if(!map.getLayer(spec.id))map.addLayer(spec,before);map.setLayoutProperty(spec.id,'visibility','visible');}signatures.set(map,sig);context.front?.();
 }else if(group){leafletGroup=L.layerGroup().addTo(group);const z=context.zoom();if(z>=11)L.geoJSON(d,{filter:f=>f.geometry.type!=='Point'||z>=14,style:f=>({color:f.properties.color,weight:f.properties.role==='wall'?1.8:1.2,fill:/Polygon$/.test(f.geometry.type),fillOpacity:f.properties.role==='area'?.08:.18}),pointToLayer:(f,p)=>L.circleMarker(p,{radius:3.5,color:'white',weight:1,fillColor:f.properties.color,fillOpacity:1}),onEachFeature:(f,l)=>{l.bindPopup(()=>html(f.properties));if(z>=15&&f.properties.label!==false&&(f.properties.role!=='area'||f.properties.boundaryLabel))l.bindTooltip(esc(f.properties.displayName),{permanent:true,direction:f.geometry.type==='Point'?'bottom':'center',offset:f.geometry.type==='Point'?[0,6]:[0,0]});}}).addTo(leafletGroup);for(const f of names.features)if(z<15)L.circleMarker([f.geometry.coordinates[1],f.geometry.coordinates[0]],{radius:4,color:'white',weight:1,fillColor:f.properties.color,fillOpacity:1}).bindTooltip(esc(f.properties.displayName),{permanent:true,direction:'bottom'}).bindPopup(()=>html(f.properties)).addTo(leafletGroup);}
 }catch(e){console.warn('Classical sites',e);}}
 function click(map,event){if(!enabled())return false;const available=layers.filter(id=>map.getLayer(id));if(!available.length)return false;const p=event.point,hits=map.queryRenderedFeatures([[p.x-4,p.y-4],[p.x+4,p.y+4]],{layers:available}),f=hits.find(f=>f.properties.role&&f.properties.role!=='area')||hits[0];if(!f)return false;new maplibregl.Popup().setLngLat(event.lngLat).setHTML(html(f.properties)).addTo(map);return true;}
 function init(c){context=c;if(typeof document!=='undefined')document.addEventListener('click',e=>{const b=e.target.closest?.('[data-classical-focus]');if(!b)return;e.preventDefault();e.stopPropagation();focus(b.dataset.classicalFocus);},true);}
 function heritageKey(name){return ({Aphrodisias:'aphrodisias','阿佛洛狄西亚斯':'aphrodisias','以弗所':'ephesus','赫拉波利斯和帕穆克卡莱':'hierapolis','Pergamon and its Multi-Layered Cultural Landscape':'pergamon','帕加马及其多层文化景观':'pergamon','特洛伊考古遗址':'troy','雅典卫城':'athens','罗马历史中心，享受治外法权的罗马教廷建筑和缪拉圣保罗弗利':'rome','伊斯坦布尔历史区域':'istanbul','哈图莎：希泰首都':'hattusa','哈图莎：赫梯首都':'hattusa'})[name]||'';}
 return {init,sync,click,collection,siteFeatures,focus,heritageKey};
})();
