/* Actual polygon mosaic, ordered by verified source scale metadata. */
(function(root){
  const p=root.GeologyProviders,cache=new Map(),pending=new Map();
  const metaUrl=root.document?.currentScript?.src?new URL('data/geology/source-scales.json?v=1',root.document.currentScript.src).href:'data/geology/source-scales.json?v=1';
  let metadata,metadataRequest;
  async function sources(signal){if(signal?.aborted)throw new DOMException('Aborted','AbortError');if(!metadata){if(!metadataRequest)metadataRequest=(async()=>{const r=await fetch(metaUrl,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Source metadata unavailable');const data=(await r.json()).data;if(!Array.isArray(data))throw Error('Invalid source metadata');metadata=new Map(data.map(s=>[Number(s.source_id),s]));})().finally(()=>{metadataRequest=null;});await metadataRequest;}if(signal?.aborted)throw new DOMException('Aborted','AbortError');return metadata;}

  const denominator=s=>Number(s?.map_scale||s?.scale_denominator);
  function order(a,b,meta){const sa=meta.get(Number(a.unit.source_id)),sb=meta.get(Number(b.unit.source_id)),na=denominator(sa),nb=denominator(sb);if(na>=1000&&nb>=1000&&na!==nb)return nb-na;const ranks={tiny:0,small:1,medium:2,large:3};return (ranks[sa?.scale]??-1)-(ranks[sb?.scale]??-1)||Number(a.unit.source_id)-Number(b.unit.source_id);}
  async function fullTile(z,x,y,signal){const key=`${z}/${x}/${y}`;if(signal?.aborted)throw new DOMException('Aborted','AbortError');if(cache.has(key))return cache.get(key);if(!pending.has(key))pending.set(key,(async()=>{const r=await fetch(`https://tiles.macrostrat.org/v2/maps/${key}`,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(`All-map tile HTTP ${r.status}`);const data=p.decode(await r.arrayBuffer());try{const labels=new Map((await p.readTile(z,x,y)).map(f=>[f.unit.source_id+':'+f.unit.legend_id,f.unit]));for(const f of data){const label=labels.get(f.unit.source_id+':'+f.unit.legend_id);if(label)f.unit={...label,...f.unit,name:f.unit.name||label.name,age:f.unit.age||label.age,t_int_name:f.unit.t_int_name||label.t_int_name,lith:f.unit.lith||label.lith};}}catch(error){/* Geometry remains usable if optional descriptive fields cannot be read. */}cache.set(key,data);if(cache.size>256)cache.delete(cache.keys().next().value);return data;})().finally(()=>pending.delete(key)));const data=await pending.get(key);if(signal?.aborted)throw new DOMException('Aborted','AbortError');return data;}

  async function features(z,x,y,signal){const meta=await sources(signal),items=[];for(const ancestor of [4,6,8].filter(a=>a<z)){const factor=2**(z-ancestor),px=Math.floor(x/factor),py=Math.floor(y/factor);const list=ancestor===4?await p.readTile(4,px,py,signal):await fullTile(ancestor,px,py,signal);for(const f of list)items.push({...f,unit:{...f.unit,overview:ancestor===4},factor,offsetX:x-px*factor,offsetY:y-py*factor});}for(const f of await(z<4?p.readTile(z,x,y,signal):fullTile(z,x,y,signal)))items.push({...f,factor:1,offsetX:0,offsetY:0});for(const f of items){if(!f.bounds){let left=Infinity,top=Infinity,right=-Infinity,bottom=-Infinity;for(const ring of f.rings)for(const pt of ring){left=Math.min(left,pt.x);right=Math.max(right,pt.x);top=Math.min(top,pt.y);bottom=Math.max(bottom,pt.y);}f.bounds=[left,top,right,bottom];}}return items.filter(f=>p.intersects(f,f.offsetX/f.factor*f.extent,f.offsetY/f.factor*f.extent,(f.offsetX+1)/f.factor*f.extent,(f.offsetY+1)/f.factor*f.extent)).sort((a,b)=>order(a,b,meta));}
  function pointIn(f,x,y){const px=(x+f.offsetX)/f.factor*f.extent,py=(y+f.offsetY)/f.factor*f.extent;if(f.bounds&&(px<f.bounds[0]||px>f.bounds[2]||py<f.bounds[1]||py>f.bounds[3]))return false;return p.contains(f.rings,px,py);}
  async function inspect(lng,lat,level,signal){const z=p.zoom(level+1),[px,py]=p.tilePoint(lng,lat,z),x=Math.floor(px),y=Math.min(2**z-1,Math.floor(py));const list=await features(z,x,y,signal);const item=list.filter(f=>pointIn(f,px-x,py-y)).at(-1);return item?[item.unit]:[];}
  function draw(ctx,f,color){ctx.beginPath();for(const ring of f.rings){for(let i=0;i<ring.length;i++){const pt=ring[i],x=(pt.x/f.extent*f.factor-f.offsetX)*256,y=(pt.y/f.extent*f.factor-f.offsetY)*256;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.closePath();}ctx.fillStyle=color;ctx.fill('evenodd');}
  async function paint(z,x,y,signal,picking=false){const list=await features(z,x,y,signal),canvas=root.document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d',{willReadFrequently:picking});list.forEach((f,i)=>{const color=picking?`rgb(${(i+1)&255},${((i+1)>>8)&255},${((i+1)>>16)&255})`:(/^#[\da-f]{6}$/i.test(f.unit.color||'')?f.unit.color:'#bcbcbc');draw(ctx,f,color);});if(signal?.aborted)throw new DOMException('Aborted','AbortError');return {canvas,list,ctx};}
  async function legend(boxes,level,signal){const z=p.zoom(level+1),n=2**z,tasks=[],result=[];for(const[w,s,e,north]of boxes){const[a,b]=p.tilePoint(w,north,z),[c,d]=p.tilePoint(e===180?179.999999:e,s,z);for(let x=Math.floor(a);x<=Math.floor(c);x++)for(let y=Math.max(0,Math.floor(b));y<=Math.min(n-1,Math.floor(d));y++)tasks.push({x,y,a,b,c,d});}if(tasks.length>512)throw Error('Viewport too large');let next=0;await Promise.all(Array.from({length:Math.min(4,tasks.length)},async()=>{while(next<tasks.length){const t=tasks[next++],r=await paint(z,t.x,t.y,signal,true);const left=Math.max(0,Math.floor((t.a-t.x)*256)),top=Math.max(0,Math.floor((t.b-t.y)*256)),right=Math.min(256,Math.ceil((t.c-t.x)*256)),bottom=Math.min(256,Math.ceil((t.d-t.y)*256));if(right<=left||bottom<=top)continue;const data=r.ctx.getImageData(left,top,right-left,bottom-top).data,ids=new Set();for(let i=0;i<data.length;i+=4){const id=data[i]|data[i+1]<<8|data[i+2]<<16;if(data[i+3]===255&&id&&!ids.has(id)&&r.list[id-1]){const pixel=i/4,px=(left+pixel%(right-left)+.5)/256,py=(top+Math.floor(pixel/(right-left))+.5)/256;if(pointIn(r.list[id-1],px,py)&&!r.list.slice(id).some(f=>pointIn(f,px,py)))ids.add(id);}}for(const id of ids)if(r.list[id-1])result.push(r.list[id-1].unit);}}));return result;}
  const registered=new WeakSet();
  function register(maplibre){if(registered.has(maplibre))return;maplibre.addProtocol('geology-auto',async(request,controller)=>{const m=request.url.match(/\/tiles\/(\d+)\/(\d+)\/(\d+)/);if(!m)throw Error('Invalid geology tile');const {canvas}=await paint(...m.slice(1).map(Number),controller.signal);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Geology tile encoding failed');return {data:await blob.arrayBuffer()};});registered.add(maplibre);}
  function leaflet(map,group,options){const L=root.L,controllers=new WeakMap();const Layer=L.GridLayer.extend({createTile(coords,done){const tile=root.document.createElement('canvas');tile.width=tile.height=256;const controller=new AbortController();controllers.set(tile,controller);paint(p.zoom(coords.z+1),coords.x,coords.y,controller.signal).then(({canvas})=>{if(controller.signal.aborted)return;tile.getContext('2d').drawImage(canvas,0,0);done(null,tile);}).catch(error=>{if(!controller.signal.aborted)done(error,tile);});return tile;}});const layer=new Layer({...options,tileSize:128,maxNativeZoom:13,maxZoom:19});layer.on('tileunload',event=>controllers.get(event.tile)?.abort());layer.addTo(group);return layer;}
  // Explicit scale modes filter the maps compilation; automatic uses server PNGs.
  const scaleProviders=new Map();
  function scaleProvider(category){if(scaleProviders.has(category))return scaleProviders.get(category);
    async function units(z,x,y,signal){const meta=await sources(signal);let data;try {data=await fullTile(z,x,y,signal);}catch(error){if(signal?.aborted)throw error;data=await p.readTile(z,x,y,signal);}return data.filter(f=>meta.get(Number(f.unit.source_id))?.scale===category);}
    const maxzoom={large:14,medium:8,small:5}[category];
    const adapter={id:'scale-'+category,render:{tiles:['geology-scale://'+category+'/{z}/{x}/{y}'],tileSize:256,maxzoom},
      async inspect(lng,lat,level,signal){const z=Math.min(maxzoom,p.zoom(level)),[px,py]=p.tilePoint(lng,lat,z);const selected=(await units(z,Math.floor(px),Math.floor(py),signal)).filter(f=>p.contains(f.rings,(px%1)*f.extent,(py%1)*f.extent)).at(-1);return selected?[selected.unit]:[];},
      readFeatures:units,
      async legend(boxes,level,signal){return p.scanLegend(boxes,Math.min(maxzoom,level),signal,units);},
      async paint(z,x,y,signal){const canvas=root.document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');for(const f of await units(z,x,y,signal))draw(ctx,{...f,factor:1,offsetX:0,offsetY:0},f.unit.color||'#bcbcbc');return canvas;}
    };scaleProviders.set(category,adapter);return adapter;}
  const scaleRegistered=new WeakSet();
  function registerScales(gl){if(scaleRegistered.has(gl))return;gl.addProtocol('geology-scale',async(request,controller)=>{const m=request.url.match(/geology-scale:\/\/(large|medium|small)\/(\d+)\/(\d+)\/(\d+)/);if(!m)throw Error('Invalid scale tile');const canvas=await scaleProvider(m[1]).paint(...m.slice(2).map(Number),controller.signal);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));return {data:await blob.arrayBuffer()};});scaleRegistered.add(gl);}
  function scaleLeaflet(group,category,options){const adapter=scaleProvider(category),L=root.L;const Layer=L.GridLayer.extend({createTile(coords,done){const tile=root.document.createElement('canvas');tile.width=tile.height=256;const controller=new AbortController();tile._geologyAbort=controller;adapter.paint(coords.z,coords.x,coords.y,controller.signal).then(canvas=>{if(controller.signal.aborted)return;tile.getContext('2d').drawImage(canvas,0,0);done(null,tile);}).catch(error=>{if(!controller.signal.aborted)done(error,tile);});return tile;}});const layer=new Layer({...options,tileSize:256,maxNativeZoom:adapter.render.maxzoom,maxZoom:19});layer.on('tileunload',e=>e.tile._geologyAbort?.abort());return layer.addTo(group);}
  root.GeologyAuto={id:'macrostrat-auto',render:{tiles:['geology-auto://tiles/{z}/{x}/{y}'],tileSize:128,maxzoom:14},sources,scaleProvider,registerScales,scaleLeaflet,order,features,pointIn,inspect,legend,paint,register,leaflet};
  if(typeof module!=='undefined')module.exports=root.GeologyAuto;
})(typeof window!=='undefined'?window:globalThis);
