const PompeiiSites=(()=>{
 let context,data,pending,leafletGroup;
 const ids=['pompeii-fill','pompeii-lines','pompeii-points','pompeii-labels','pompeii-city-label'],signatures=new WeakMap(),color='#bd9200';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function enabled(){const o=context.state().mapOverlays;return Boolean(o.chinaAncientCapitals&&o.ancientCapitalWalls&&o.ancientCapitalQinHanWalls!==false);}
 async function load(){if(data)return data;pending||=fetch('data/pompeii/sites.geojson?v=1').then(r=>{if(!r.ok)throw Error(r.status);return r.json();}).then(d=>data=d).finally(()=>pending=null);return pending;}
 function collection(){const en=context.language()==='en';return {type:'FeatureCollection',features:(data?.features||[]).map(f=>({...f,properties:{...f.properties,displayName:en?f.properties.enName:f.properties.name}}))};}
 function point(f){if(f.geometry.type==='Point')return f.geometry.coordinates;const r=f.geometry.coordinates[0].slice(0,-1);return r.reduce((s,p)=>[s[0]+p[0]/r.length,s[1]+p[1]/r.length],[0,0]);}
 function html(p){const en=context.language()==='en';return '<b>'+esc(en?p.enName:p.name)+'</b><p>'+esc(en?'Pompeii · Roman Republic / Roman Empire · World Heritage component 829': '庞贝 · 罗马共和国／罗马帝国 · 世界遗产829组成部分')+'</p><p>'+esc(en?'Public OSM geometry; not a surveyed legal protection boundary.':p.note)+'</p><small>© OpenStreetMap contributors · ODbL</small><br><a target="_blank" rel="noopener" href="'+esc(p.sourceUrl)+'">'+(en?'Source geometry':'矢量来源')+' ↗</a><br><a target="_blank" rel="noopener" href="'+esc(p.referenceUrl)+'">'+(en?'Official site map':'官方遗址图')+' ↗</a>';}
 async function sync(map,group){if(!context)return;if(leafletGroup){leafletGroup.remove();leafletGroup=null;}if(!enabled()){if(map){for(const id of ids)if(map.getLayer(id))map.setLayoutProperty(id,'visibility','none');signatures.delete(map);}return;}
 try{await load();if(!enabled())return;const d=collection(),labels={type:'FeatureCollection',features:d.features.filter(f=>f.properties.role!=='city').map(f=>({...f,properties:{...f.properties,pointFeature:f.geometry.type==='Point'},geometry:{type:'Point',coordinates:point(f)}}))},city={type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[14.487,40.7516]},properties:{displayName:context.language()==='en'?'Pompeii':'庞贝古城'}}]};
 if(map){const sig=context.language();if(signatures.get(map)===sig&&map.getSource('pompeii-sites'))return;
 for(const [id,value] of [['pompeii-sites',d],['pompeii-site-labels',labels],['pompeii-city',city]]){if(map.getSource(id))map.getSource(id).setData(value);else map.addSource(id,{type:'geojson',data:value});}
 const before=map.getStyle().layers.find(l=>l.type==='symbol')?.id;
 const specs=[{id:ids[0],type:'fill',source:'pompeii-sites',minzoom:11,filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':color,'fill-opacity':['case',['==',['get','role'],'city'],.10,.20]}},{id:ids[1],type:'line',source:'pompeii-sites',minzoom:11,filter:['==',['geometry-type'],'Polygon'],paint:{'line-color':color,'line-width':['case',['==',['get','role'],'city'],1.8,1.2]}},{id:ids[2],type:'circle',source:'pompeii-sites',minzoom:14,filter:['==',['geometry-type'],'Point'],paint:{'circle-radius':3.5,'circle-color':color,'circle-stroke-color':'white','circle-stroke-width':1}},{id:ids[3],type:'symbol',source:'pompeii-site-labels',minzoom:15,layout:{'text-field':['get','displayName'],'text-font':['Open Sans Regular','Arial Unicode MS Regular'],'text-size':12,'text-max-width':12,'text-anchor':['case',['==',['get','pointFeature'],true],'top','center'],'text-offset':['case',['==',['get','pointFeature'],true],['literal',[0,.8]],['literal',[0,0]]],'text-justify':'center','text-padding':5},paint:{'text-color':color,'text-halo-color':'white','text-halo-width':1.5}},{id:ids[4],type:'symbol',source:'pompeii-city',minzoom:11,maxzoom:15,layout:{'text-field':['get','displayName'],'text-font':['Open Sans Regular','Arial Unicode MS Regular'],'text-size':13,'text-anchor':'center'},paint:{'text-color':color,'text-halo-color':'white','text-halo-width':1.5}}];
 for(const spec of specs){if(!map.getLayer(spec.id))map.addLayer(spec,before);map.setLayoutProperty(spec.id,'visibility','visible');}signatures.set(map,sig);context.front?.();
 }else if(group){leafletGroup=L.layerGroup().addTo(group);const z=context.zoom();if(z>=11)L.geoJSON(d,{style:f=>({color,weight:f.properties.role==='city'?1.8:1.2,fillOpacity:f.properties.role==='city'?.10:.20}),pointToLayer:(f,p)=>L.circleMarker(p,{radius:3.5,color:'white',weight:1,fillColor:color,fillOpacity:1}),filter:f=>f.geometry.type!=='Point'||z>=14,onEachFeature:(f,l)=>{l.bindPopup(()=>html(f.properties));if(z>=15&&f.properties.role!=='city')l.bindTooltip(esc(f.properties.displayName),{permanent:true,direction:f.geometry.type==='Point'?'bottom':'center',offset:f.geometry.type==='Point'?[0,6]:[0,0]});}}).addTo(leafletGroup);}
 }catch(e){console.warn('Pompeii sites',e);}}
 function click(map,event){if(!enabled())return false;const layers=ids.slice(0,4).filter(id=>map.getLayer(id));if(!layers.length)return false;const p=event.point,hits=map.queryRenderedFeatures([[p.x-4,p.y-4],[p.x+4,p.y+4]],{layers}),f=hits.find(f=>f.properties.role!=='city')||hits[0];if(!f)return false;new maplibregl.Popup().setLngLat(event.lngLat).setHTML(html(f.properties)).addTo(map);return true;}
 return {init:c=>context=c,sync,click,collection};
})();
