const fs=require('fs'),assert=require('assert'),vm=require('vm'),d=JSON.parse(fs.readFileSync('data/classical-sites/sites.geojson')),c=require('../data/classical-sites/catalog.json');
assert.equal(c.sites.length,11);assert.equal(d.features.length,359);assert.equal(new Set(d.features.map(f=>f.properties.id)).size,359);assert.equal(c.sites.filter(s=>s.tentative).length,2);
for(const f of d.features){assert(/[\u4e00-\u9fff]/.test(f.properties.name));assert(f.properties.referenceUrl);assert(f.properties.sourceUrl);if(f.geometry.type==='Polygon'||f.geometry.type==='MultiPolygon'){const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;for(const rings of polygons)for(const r of rings){assert(r.length>=4);assert.deepEqual(r[0],r.at(-1));assert(r.flat().every(Number.isFinite));}}}
assert(d.features.some(f=>f.geometry.type==='MultiPolygon'&&f.properties.name==='卫城山门'));assert(d.features.find(f=>f.properties.name==='罗马斗兽场').geometry.type==='Polygon');assert(d.features.some(f=>f.geometry.type==='Polygon'&&f.geometry.coordinates.length>1),'Preserve holes when present in original geometry');assert(d.features.filter(f=>f.properties.role==='wall').some(f=>f.geometry.type==='LineString'));assert(d.features.find(f=>f.properties.name.includes('钙华台地')).properties.role==='natural');
const requirePeriods=require('../historical-periods.js').keys;const o={worldHeritage:true,chinaAncientCapitals:true,ancientCapitalWalls:true},layers=new Map(),sources=new Map(),focuses=[],map={getStyle:()=>({layers:[]}),getLayer:id=>layers.get(id),getSource:id=>sources.get(id),addSource:(id,s)=>sources.set(id,{...s,setData(v){this.data=v;}}),addLayer:s=>layers.set(s.id,s),setLayoutProperty:(id,k,v)=>layers.get(id)[k]=v};let mergedMarkerVisible=false,lang='zh',fetches=0;const ctx={console,HistoricalPeriods:require('../historical-periods.js'),fetch:async u=>{fetches++;return {ok:true,json:async()=>u.includes('catalog')?c:d};}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('classical-sites.js','utf8')+'\nthis.api=ClassicalSites;',ctx);ctx.api.init({mergedMarkerVisible:key=>mergedMarkerVisible&&key==='hattusa',state:()=>({mapOverlays:o}),language:()=>lang,front:()=>{},focus:(p,z)=>focuses.push([p,z])});
(async()=>{
 await ctx.api.sync(map);assert.equal(layers.size,7);assert.equal(layers.get('classical-sites-labels').layout['text-anchor'][2],'top');assert.ok(sources.get('classical-sites-labels').data.features.every(f=>typeof f.properties.pointFeature==='boolean'),'Distinguish actual points from polygon labels');assert.equal(ctx.api.siteFeatures().features.length,11);const heritage=JSON.parse(fs.readFileSync('data/world-heritage.json')).items.find(s=>s.id==='whc-377');assert.deepEqual(c.sites.find(s=>s.key==='hattusa').center,[heritage.lng,heritage.lat]);mergedMarkerVisible=true;await ctx.api.sync(map);assert(!sources.get('classical-sites-names').data.features.some(f=>f.properties.siteKey==='hattusa'),'Avoid duplicate heritage/root marker');assert(sources.get('classical-sites').data.features.some(f=>f.properties.siteKey==='hattusa'),'Keep site details when markers merge');mergedMarkerVisible=false;await ctx.api.sync(map);assert(sources.get('classical-sites-names').data.features.some(f=>f.properties.siteKey==='hattusa'),'Keep fallback marker when heritage hidden');assert(sources.get('classical-sites-labels').data.features.some(f=>f.properties.id==='hattusa-way-114570703'),'Palace area must have a rendered label');assert(sources.get('classical-sites-labels').data.features.some(f=>f.properties.id==='hattusa-vici-24115'&&f.properties.pointFeature),'Southern Fort label must retain its point marker');
 assert(ctx.api.collection().features.filter(f=>['perge','aspendos'].includes(f.properties.siteKey)).every(f=>!f.properties.heritageId&&f.properties.tentative),'Tentative status is retained in wall details');
 await ctx.api.sync(map);assert.equal(fetches,2);lang='en';await ctx.api.sync(map);assert.equal(sources.get('classical-sites').data.features[0].properties.displayName,d.features[0].properties.enName);
 o.ancientCapitalPeriods=Object.fromEntries(requirePeriods.map(k=>[k,false]));await ctx.api.sync(map);assert.equal(ctx.api.collection().features.length,359,'Capital-marker era selection must not hide wall details');
 o.ancientCapitalWalls=false;await ctx.api.sync(map);assert.equal(ctx.api.collection().features.length,0);assert([...layers.values()].every(l=>l.visibility==='none'),'World Heritage cannot bypass wall master');
 o.ancientCapitalWalls=true;o.ancientCapitalQinHanWalls=false;await ctx.api.sync(map);assert(!ctx.api.collection().features.some(f=>f.properties.period==='秦汉'));assert(ctx.api.collection().features.some(f=>f.properties.period==='魏晋南北朝'));
 await ctx.api.focus('perge');assert(focuses.length);assert.equal(o.ancientCapitalWalls,true);assert.equal(o.ancientCapitalQinHanWalls,true);assert.equal(o.ancientCapitalPeriods['秦汉'],false,'Focus changes wall controls, preserving marker era choices');
 const water=ctx.api.collection().features.find(f=>f.properties.role==='water');assert.equal(water.properties.color,'#277caa');for(const f of ctx.api.collection().features.filter(f=>!['water','natural'].includes(f.properties.role)))assert.equal(f.properties.color,ctx.HistoricalPeriods.colors[f.properties.period]);
 o.chinaAncientCapitals=false;await ctx.api.sync(map);assert([...layers.values()].every(l=>l.visibility==='none'));console.log('PASS: classical wall master and era controls, independent marker/heritage controls, period colours, focus and bilingual refresh');
})().catch(e=>{console.error(e);process.exitCode=1;});
