const assert = require('node:assert/strict');
const api = require('../earthquake-online.js');
const fs = require('node:fs');
const path = require('node:path');
const css = fs.readFileSync(path.join(__dirname, '../styles.css'), 'utf8');
assert.match(css, /#earthquakeLegend\s*\{\s*pointer-events:\s*auto;\s*\}/, 'earthquake legend buttons must accept real pointer clicks');
const time = Date.UTC(2024, 0, 1, 1, 2, 3);
const attributes = { id: 'us-test', time, latitude: 10, longitude: 179.95, mag: 5.1, depth: 0, place: 'Test', magType: 'mw' };
assert.deepEqual(api.yearPreset('all', 2026), [null, null]);
assert.deepEqual(api.yearPreset('1900', 2026), [1900, 2026]);
assert.deepEqual(api.yearPreset('before1900', 2026), [null, 1899]);
assert.equal(api.yearPreset('50', 2026), null);
assert.deepEqual(api.yearPreset('10', 2026), [2017, 2026]);
assert.deepEqual(api.yearDomain(null, null, -2150, 2026), { min: -2150, max: 2026 });
assert.deepEqual(api.yearDomain(1900, 2026, -2150, 2026), { min: 1900, max: 2026 });
assert.deepEqual(api.yearDomain(-500, 1800, -2150, 2026), { min: -500, max: 2026 });
assert.equal(api.yearPosition(-2150, -2150, 2026), 0);
assert.equal(api.yearPosition(1900, -2150, 2026), 1500);
assert.equal(api.yearPosition(2026, -2150, 2026), 10000);
for (const year of [-2150, -1000, 0, 1800, 1900, 1950, 2026]) assert.equal(api.positionYear(api.yearPosition(year, -2150, 2026), -2150, 2026), year);
assert.deepEqual(api.extents(170, -10, 190, 10), [[170, -10, 180, 10], [-180, -10, -170, 10]]);
assert.deepEqual(api.extents(-220, -100, 220, 100), [[-180, -90, 180, 90]]);
assert.equal(api.normalize({ ...attributes, latitude: null }), null);
assert.equal(api.normalize(attributes).eqDepth, 0);
const online = api.normalize(attributes);
const local = { ...online, id: 'local', longitude: -179.98, source: 'NOAA/NCEI' };
assert.equal(api.merge([local], [online]).length, 1, 'nearby timed duplicate across dateline is merged');
assert.equal(api.merge([{ ...local, hour: undefined }], [online]).length, 2, 'do not assume date-only events are duplicates');
assert.equal(api.merge([{ ...local, year: -100 }], [online]).length, 2, 'retain ancient history');
(async () => {
  const urls = [], updates = [];
  const result = await api.query({ bounds: [0, 0, 20, 20], minimum: 4, startYear: 2024, endYear: 2025, onPage: items => updates.push(items.length), fetcher: async url => {
    const params = new URL(url).searchParams; urls.push(params);
    return { ok: true, json: async () => ({ features: [{ attributes: { ...attributes, id: urls.length === 1 ? 'first' : 'second' } }], exceededTransferLimit: urls.length === 1 }) };
  } });
  assert.equal(result.items.length, 2); assert.equal(result.truncated, false);
  assert.deepEqual(updates, [1, 2]);
  assert.equal(urls[1].get('resultOffset'), '2000');
  assert.match(urls[0].get('where'), /mag >= 4/);
  assert.match(urls[0].get('where'), /2026-01-01/);
  assert.equal(urls[0].get('inSR'), '4326');
  await assert.rejects(api.query({ bounds: [0, 0, 20, 20], fetcher: async () => ({ ok: true, json: async () => ({ error: { message: 'Denied' } }) }) }), /Denied/);
  await assert.rejects(api.query({ bounds: [0, 0, 20, 20], fetcher: async () => ({ ok: true, json: async () => ({ features: [], exceededTransferLimit: true }) }) }), /incomplete page/);
  const dense = await api.query({ bounds: [0, 0, 20, 20], fetcher: async url => {
    const offset = Number(new URL(url).searchParams.get('resultOffset'));
    return { ok: true, json: async () => ({ features: Array.from({ length: 2000 }, (_, i) => ({ attributes: { ...attributes, id: String(offset + i) } })), exceededTransferLimit: true }) };
  } });
  assert.equal(dense.items.length, 20000); assert.equal(dense.truncated, true);
  const app = fs.readFileSync(path.join(__dirname, '../app.js'), 'utf8');
  assert.match(app, /controller !== earthquakeOnlineController/);
  assert.match(app, /mousemove", "earthquake-points"/);
  assert.match(app, /earthquakePopupContent\(props, true\)/);
  const sliderInput = app.slice(app.indexOf('input?.addEventListener("input", () => {', app.indexOf('for (const [id, index]')), app.indexOf('input?.addEventListener("change", () => {', app.indexOf('for (const [id, index]')));
  assert.match(sliderInput, /earthquakeYearDraft/);
  assert.doesNotMatch(sliderInput, /refreshEarthquakeOnline|applyEarthquakeYears|saveUiStateSoon/);
  const refresh = app.slice(app.indexOf('function refreshEarthquakeOnline('), app.indexOf('function earthquakePopupContent('));
  assert.ok(refresh.indexOf('if (!force && key === earthquakeOnlineKey) return;') < refresh.indexOf('clearTimeout(earthquakeOnlineTimer);', refresh.indexOf('const key =')), 'same-view rerender must not cancel pending query');
  const ancient = await api.query({ bounds: [0, 0, 20, 20], endYear: 1899, fetcher: () => { throw new Error('must not query ancient online data'); } });
  assert.equal(ancient.items.length, 0);
  console.log('PASS: online earthquake paging, year/extent filters, deduplication, errors, density limit and hover integration');
})().catch(error => { console.error(error); process.exitCode = 1; });
