const assert=require('node:assert/strict');
class Element {constructor(tag){this.tag=tag;this.children=[];this.attrs={};this.style={};this.events={};this.hidden=false;this.textContent='';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;this.textContent='';}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,fn){this.events[k]=fn;}click(){this.events.click?.();}focus(){}}
global.document={createElement:t=>new Element(t),getElementById:()=>new Element('div')};
const popups=[];class Popup{constructor(){popups.push(this)}setLngLat(){return this}setDOMContent(content){this.content=content;return this}addTo(){return this}on(k,fn){this.close=fn;return this}remove(){this.removed=true;this.close?.();}}
global.maplibregl={Popup};let resolveOld;
const unit=(name,id)=>({name,map_id:id,source_id:154,t_int_name:'Neogene',t_age:2.588,b_age:23.03,lith:'sedimentary rocks'});
global.GeologyProviders={normalizeMode:m=>['global','large','medium','small','asia'].includes(m)?m:'auto',scale:()=>null,chooseAt:()=>({inspect:async(lng)=>lng===1?new Promise(resolve=>{resolveOld=resolve}):[unit('Displayed new',2)]})};
global.fetch=async url=>({ok:true,json:async()=>String(url).includes('/defs/')?{success:{data:[{source_id:154,scale:'tiny'},{source_id:133,scale:'medium'},{source_id:9,scale:'large'}]}}:{success:{data:[{...unit('Different source',3),source_id:133},{...unit('Finest source',4),source_id:9},unit('Displayed new',2)]}}});
const legend=require('../geology-legend');const map={getZoom:()=>4};const walk=e=>[e,...e.children.flatMap(walk)];const text=e=>walk(e).map(n=>n.textContent).join(' ');
(async()=>{const old=legend.inspect(map,1,30,false,false);await Promise.resolve();await legend.inspect(map,2,30,false,false);const popup=popups.at(-1);resolveOld([unit('Stale old',1)]);await old;assert.match(text(popup.content),/Displayed new/);assert.doesNotMatch(text(popup.content),/Stale old/);const panels=walk(popup.content).filter(e=>e.attrs.role==='tabpanel');assert.equal(panels.length,4);assert.equal(panels[0].hidden,true);assert.equal(panels[1].hidden,true);assert.equal(panels[3].hidden,false);assert.match(text(panels[3]),/Displayed new/);assert.doesNotMatch(text(panels[3]),/Different source/);assert.match(text(panels[1]),/Different source/);assert.match(text(panels[2]),/此处未查询到该尺度的记录/);const tabs=walk(popup.content).filter(e=>e.attrs.role==='tab');assert.deepEqual(tabs.map(t=>t.textContent),['局部详图','区域地质图','洲际地质图','全球概略图 · 当前']);tabs[0].click();assert.equal(panels[0].hidden,false);assert.equal(panels[3].hidden,true);tabs[0].events.keydown({key:'ArrowLeft',preventDefault(){}});assert.equal(panels[3].hidden,false);assert.equal(legend.scaleGroups([{source:{scale:'tiny'},primary:true},{source:{scale:'tiny'}}],false).length,1);assert.equal(legend.scaleGroups([{source:{}},{source:{}}],false).length,1);legend.update(null,false,false);assert.equal(popup.removed,true);global.GeologyProviders.chooseAt=()=>({inspect:async()=>{throw Error('timeout')}});await legend.inspect(map,2,30,false,false);assert.match(text(popups.at(-1).content),/查询失败/);assert(walk(popups.at(-1).content).some(e=>e.tag==='button'&&e.textContent==='重试'));global.GeologyProviders.chooseAt=()=>({inspect:async()=>[]});
global.fetch=async()=>({ok:true,json:async()=>({success:{data:[]}})});
await legend.inspect(map,2,30,false,false);let empty=text(popups.at(-1).content);assert.match(empty,/此处暂无地质数据/);assert.doesNotMatch(empty,/以下|对照/);assert.equal(walk(popups.at(-1).content).filter(e=>e.attrs.role==='tab').length,4);
await legend.inspect(map,2,30,true,false);assert.match(text(popups.at(-1).content),/No geology data is available here/);
global.fetch=async()=>({ok:true,json:async()=>({success:{data:[unit('Comparison only',6)]}})});
await legend.inspect(map,2,30,false,false);assert.match(text(popups.at(-1).content),/其他尺度的查询记录/);assert.match(text(popups.at(-1).content),/Comparison only/);assert.match(text(popups.at(-1).content),/其他查询记录/);assert.match(text(popups.at(-1).content),/未显示在当前地图中/);assert.doesNotMatch(text(popups.at(-1).content),/图源对照/);
global.fetch=async()=>{throw Error('comparison timeout')};await legend.inspect(map,2,30,false,false);empty=text(popups.at(-1).content);assert.match(empty,/其他记录查询失败/);assert.doesNotMatch(empty,/以下|对照/);
global.fetch=async url=>{if(new URL(url).searchParams.get('scale')==='small')throw Error('continental timeout');return {ok:true,json:async()=>({success:{data:[]}})}};await legend.inspect(map,2,30,false,false);const failedPanels=walk(popups.at(-1).content).filter(e=>e.attrs.role==='tabpanel');assert.match(text(failedPanels[2]),/该尺度查询失败/);assert.match(text(failedPanels[1]),/此处未查询到该尺度的记录/);
legend.update(null,false,false,'medium');await legend.inspect(map,2,30,false,false);const selectedPanels=walk(popups.at(-1).content).filter(e=>e.attrs.role==='tabpanel');assert.equal(selectedPanels[1].hidden,false);assert.equal(selectedPanels[0].hidden,true);assert.match(text(popups.at(-1).content),/区域地质图 · 已选模式/);global.fetch=async()=>{throw Error('Raster must not query Macrostrat')};global.GeologyProviders.chooseAt=()=>{throw Error('Raster must not select Macrostrat')};legend.update(null,false,false,'asia');await legend.inspect(map,2,30,false,false);assert.match(text(popups.at(-1).content),/亚洲地质影像图/);assert.doesNotMatch(text(popups.at(-1).content),/Comparison only|地图所示|Macrostrat/);assert.equal(walk(popups.at(-1).content).filter(e=>e.attrs.role==='tab').length,0);legend.closeDetail();console.log('PASS: actual displayed record, ordered scale tabs and current-scale default, stale request suppression, disable cancellation and retry');})();
