const assert = require('node:assert/strict');
const legend = require('../geology-legend.js');
assert.deepEqual(legend.windows(170, -90, 200, 90), [[170, -85, 180, 85], [-180, -85, -160, 85]]);
assert.deepEqual(legend.windows(-210, -30, 210, 30), [[-180, -30, 180, 30]]);
assert.deepEqual(legend.windows(530, -10, 550, 10), [[170, -10, 180, 10], [-180, -10, -170, 10]]);
assert.equal(legend.translateAge('Late Cenozoic - Paleoproterozoic', false), '晚新生代 - 古元古代');
assert.equal(legend.translateAge('Archean', true), 'Archean');
const older = { legend_id: 1, t_age: 66, b_age: 145, color: '#00ff00' };
const newer = { legend_id: 2, t_age: 0, b_age: 2.588, color: '#ffff00' };
assert.deepEqual(legend.units([older, newer, older]), [newer, older]);
assert.equal(legend.units([{source_id:1, map_unit_name:'a'}, {source_id:2, map_unit_name:'a'}]).length, 2);
const records = [{source_id:154, name:'Cenozoic sedimentary rocks'}, {source_id:7, name:'Neogene sedimentary'}, {source_id:133, name:'Ogallala Formation'}];
const sources = [{source_id:154, scale:'tiny'}, {source_id:7, scale:'small'}, {source_id:133, scale:'medium'}];
assert.deepEqual(legend.rankRecords(records, sources).map(record => record.unit.name), ['Ogallala Formation', 'Neogene sedimentary', 'Cenozoic sedimentary rocks']);
assert.deepEqual(legend.rankRecords(records, []).map(record => record.unit), records);
assert.deepEqual(legend.ageHierarchy('Pliocene', false), ['新生代', '新近纪', '上新世']);
assert.deepEqual(legend.ageHierarchy('Paleocene', true), ['Cenozoic', 'Paleogene', 'Paleocene']);
assert.deepEqual(legend.lithologyParts('Major:{fine alluvium,coarse alluvium}, Minor:{limestone}', false), [{label:'主要', text:'细粒冲积物、粗粒冲积物'}, {label:'次要', text:'石灰岩'}]);
assert.deepEqual(legend.lithologyParts('unknown material', false), [{label:'', text:'unknown material'}]);
console.log('PASS: geology legend antimeridian coverage, age localization, ordering and source-aware deduplication');
