const assert=require('node:assert/strict'),fs=require('node:fs');
const {category,coverage,parse}=require('../scripts/build-great-wall.cjs');
const d=JSON.parse(fs.readFileSync(require.resolve('../data/great-wall/features.geojson'),'utf8'));
const report=JSON.parse(fs.readFileSync(require.resolve('../data/great-wall/report.json'),'utf8'));
assert.equal(d.features.filter(f=>f.properties.source==='ovital').length,2454);
assert.equal(d.features.filter(f=>f.properties.source==='ovital'&&f.geometry.type==='Point').length,1894);
assert.equal(d.features.filter(f=>f.properties.source==='ovital'&&f.geometry.type==='Polygon').length,1);
assert.equal(new Set(d.features.map(f=>f.id)).size,d.features.length);
assert.ok(report.sources.every(s=>s.status==='ok'));
assert.ok(report.sources.some(s=>s.source==='greatwall-station'));
assert.ok(!d.features.some(f=>f.properties.source==='osm'));
assert.equal(category(['山西','北线军堡'],8),'fortress');
assert.equal(category(['河北','敌楼','山海关段'],7),'tower');
assert.equal(category(['山西','边墩','新平堡辖边墩'],7),'beacon');
assert.equal(category(['消失的边墙走势'],8),'lost');
const index=coverage([{properties:{category:'wall'},geometry:{type:'LineString',coordinates:[[116,40],[116.02,40]]}}]);
assert.equal(index.covered([116.01,40.0001]),true);
assert.equal(index.covered([116.01,40.02]),false);
for(const f of d.features){assert.ok(f.properties.category);assert.ok(f.geometry);if(f.properties.source!=='ovital')assert.equal(f.properties.approximate,true);}
const app=fs.readFileSync(require.resolve('../app.js'),'utf8'),html=fs.readFileSync(require.resolve('../index.html'),'utf8');
assert.match(app,/GreatWall\.sync\(mapLibreMap\)/);assert.match(app,/GreatWall\.leaflet/);assert.match(app,/GreatWall\.init/);
assert.match(app,/overlayAncientCapitals: "古都"/);assert.match(app,/overlayAncientCapitals: "Ancient Capitals"/);
assert.match(html,/compact-toggle-pair[\s\S]*?showAncientCapitalsOnMap[\s\S]*?showGreatWallOnMap/);
const css=fs.readFileSync(require.resolve('../styles.css'),'utf8');
assert.match(css,/\.great-wall-legend\s*\{\s*pointer-events:auto;/);
assert.match(css,/\.great-wall-legend > strong \{[^}]*font-size:11px/);
assert.match(css,/#greatWallCategories label \{[^}]*font-size:9px/);
assert.match(app,/greatWall: false/);
const wall=fs.readFileSync(require.resolve('../great-wall.js'),'utf8');
assert.match(wall,/data-wall-all/);
assert.doesNotMatch(html,/greatWallLegendSamples/);
assert.doesNotMatch(wall,/greatWallLegendSamples/);
assert.match(html,/<summary id="greatWallCategorySummary"><input id="greatWallSelectAll"/);
assert.doesNotMatch(wall,/class="wall-select-all"/);
assert.match(html,/id="greatWallSelectAll"[^>]*><i class="wall-disclosure"/);
assert.match(html,/id="showGreatWallHistory"[^>]*><i class="wall-disclosure"/);
assert.match(css,/summary::-webkit-details-marker \{ display:none/);
assert.match(wall,/indeterminate=selected>0&&selected<keys.length/);
assert.match(wall,/Object.fromEntries\(Object.keys\(categories\).map/);
assert.doesNotMatch(wall,/cluster:true|point_count|再分发许可待确认|redistribution permission pending/);
assert.match(wall,/installIcons\(map\)/);
assert.match(wall,/'icon-image':/);
assert.match(wall,/L\.divIcon/);
assert.match(wall,/\$\{legendSymbol\(k\)\}/);
assert.match(wall,/key==='wall'\|\|key==='lost'/);
assert.match(wall,/墩台烽燧/);
assert.doesNotMatch(wall,/墩台／烽燧/);
for(const [name,type,expected] of [['天津黄崖关长城博物馆',7,'museum'],['缙阳寺东山口墩',7,'beacon'],['营州后屯卫',7,'guard'],['潮河所',8,'guard'],['巩华城',8,'city'],['宣府镇',7,'town'],['石峡口',7,'pass'],['虎山长城',7,'landmark'],['八仙山至黄崖关',8,'wall']])assert.equal(category(['长城地图','天津北京'],type,name),expected);
assert.equal(d.features.filter(f=>f.properties.category==='unknown').length,0);
console.log('PASS: original wall dataset preserved, unified types, station supplement, distance dedup, approximate flags and UI wiring');
