const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const H=require('../historical-periods.js'),T=require('../imperial-tombs.js');
const capitals=require('../western-regions.js').merge(require('../data/china-ancient-capitals.json'),require('../data/western-regions-36.json'));
const tombs=require('../data/imperial-tombs/catalog.json');
const fangshan=tombs.items.find(x=>x.id==='lu-fangshan');
assert.equal(H.tombPeriod(fangshan),'周');
assert.match(fangshan.periodText,/周、汉/);
assert.match(fangshan.preqinPeriodBasis,/玉磬、玉璜/);
assert.match(fangshan.mapLabel,/疑似/);
assert(tombs.sources.some(x=>fangshan.sourceIds.includes(x.id)&&x.publisher==='山东省文化和旅游厅'));
assert.equal(H.keys[0],'传说');assert(!H.keys.includes('史前'));
for(const row of capitals.recordItems)assert(H.keys.includes(H.capitalPeriod(row)),row.name);
for(const site of capitals.items)assert(H.capitalPeriods(site).every(k=>H.keys.includes(k)),site.name);
for(const tomb of tombs.items)assert(H.keys.includes(H.tombPeriod(tomb)),tomb.name);
const western=capitals.recordItems.filter(x=>x.westernRegion);
assert.equal(western.length,36);assert(western.every(x=>H.capitalPeriod(x)==='秦汉'));
for(const site of capitals.items.filter(x=>x.westernRegion))assert(H.capitalPeriods(site).includes('秦汉'));
assert.equal(H.capitalPeriod({era:'十六国',dynasty:'前燕'}),'魏晋南北朝');
for(const [text,year] of [['前770年',-770],['公元前1046年',-1046],['约-2070—-1600',-2070],['230 BCE',-230],['公元前2世纪',-200],['15世纪',1401],['?—-473',null],['未定',null]])assert.equal(H.startYear(text),year,text);
assert.equal(H.capitalPeriod({era:'春秋战国',capitalYears:'-1044—-311'}),'周');
assert.equal(H.capitalPeriod({era:'春秋战国',capitalYears:'?—-473'}),'周');
assert.equal(H.capitalPeriod({era:'明清及同期',dynasty:'哲德沙尔汗国',capitalYears:'1865—1877'}),'清');
// Political continuity and posthumous attribution override a simple year cutoff.
assert.equal(H.capitalPeriod({era:'明清及同期',dynasty:'南明永历',capitalYears:'1656—1659'}),'明');
assert.equal(H.capitalPeriod({era:'宋辽夏金及同期',dynasty:'辽',capitalYears:'918—1125'}),'宋辽金西夏');
for(const id of ['han-xian','ming-zu','qing-yong']){const row=tombs.items.find(x=>x.id===id);if(row)assert.equal(T.dynastyTheme(row).key,H.tombPeriod(row));}
assert.equal(H.capitalPeriod({era:'未考',capitalYears:'未定'}),null,'no arbitrary Sui/Tang fallback');
assert.equal(H.tombPeriod({era:'先秦',preqinPeriod:'史前'}),'传说');
assert.equal(H.tombPeriod({era:'传说时代'}),'传说');
assert.equal(H.periodSelection({'传说时代':false,'史前':false}).传说,false);
assert.equal(H.periodSelection({'传说时代':true,'史前':false}).传说,true);
assert.equal(H.periodSelection({'西周':false,'春秋':false,'战国':false}).周,false);
assert.equal(H.periodSelection({'西周':false,'春秋':true,'战国':false}).周,true);
for(const raw of ['西周','东周','春秋','战国','春秋战国'])assert.equal(H.displayPeriod(raw),'周');
const reviewed=tombs.items.filter(x=>x.periodReview?.originalPeriod==='西周');
assert.equal(reviewed.length,14);
assert.equal(tombs.items.find(x=>x.id==='zhou-xianyang').preqinPeriod,'战国');
assert(reviewed.every(x=>x.periodReview.sourceIds.every(id=>tombs.sources.some(s=>s.id===id))));
assert.match(tombs.items.find(x=>x.id==='guo-m2001').periodText,/断代争议/);
const app=fs.readFileSync(require.resolve('../app.js'),'utf8');
const context={HistoricalPeriods:H,ImperialTombs:T,imperialTombChecklistItems:[],currentLanguage:'zh',checklistDoneCount:()=>0,checklistTotalCount:()=>0,checklistGroupId:(k,e)=>e,isChecklistGroupOpen:()=>false,isChecklistItemDone:()=>false,escapeHtml:String,t:()=>'',};
const parents=new Set(tombs.items.map(x=>x.parentId).filter(Boolean));
context.imperialTombChecklistItems=tombs.items.filter(x=>x.recordType==='single'||!parents.has(x.id)).sort((a,b)=>H.keys.indexOf(H.tombPeriod(a))-H.keys.indexOf(H.tombPeriod(b))||T.compareChecklistItems(a,b));
vm.createContext(context);vm.runInContext(app.slice(app.indexOf('function renderImperialTombChecklist()'),app.indexOf('function renderAchievements()')),context);
const html=context.renderImperialTombChecklist();
for(const era of ['传说','夏商','周','明','清'])assert(html.includes('<strong>'+era+'</strong>'),era);
assert(!html.includes('<strong>先秦</strong>'));assert(!html.includes('<strong>秦汉至五代</strong>'));
console.log('PASS: all 328 capitals / 278 tomb records classified, 36 Western kingdoms, signed years, missing starts, political continuity and shared checklist groups');
