const assert = require('node:assert/strict');
const fs = require('node:fs');
require('../ethnic-translations.js');
require('../ethnic-regions.js');
const data = JSON.parse(fs.readFileSync('data/language-areas.geojson', 'utf8'));
assert.equal(data.features.length, 5310);
assert.equal(data.features.filter(f=>f.properties.entryKind==='family-area').length,2);
assert.ok(data.features.some(f=>f.properties.languageId==='hmon1336'&&f.properties.family==='Hmong-Mien'));
assert.notEqual(EthnicRegions.color(data.features.find(f=>f.properties.group_==='Evenki').properties,'affinity'),'hsl(210, 12%, 55%)');
const nanai=data.features.find(f=>f.properties.languageId==='nana1257');
assert.ok(nanai.geometry.coordinates.every(p=>p[0].some(c=>c[1]>40)), 'Nanai must not contain the erroneous Yunnan polygon');
for(const id of ['atlas-miao','atlas-yao']){
 const f=data.features.find(f=>f.properties.languageId===id);
 assert.equal(f.properties.family,'Hmong-Mien');
 assert.ok(f.geometry.coordinates.some(p=>p[0].some(c=>c[0]>102.5&&c[0]<105.4&&c[1]>22.7)), 'Chinese source areas must be included');
 assert.ok(f.properties.sourceFeatureIds.length===2);
}
const restoration=JSON.parse(fs.readFileSync('data/language-source-restoration-audit.json'));
assert.equal(restoration.addedRecords,1288);
assert.equal(restoration.counts['dialect-area'],785);
assert.equal(restoration.quarantine[0].id,'2272');
assert.ok(data.features.some(f=>f.properties.languageId==='beic1239'&&f.properties.family==='Tai-Kadai'));
assert.ok(data.features.some(f=>f.properties.languageId==='dulo1243'&&f.properties.entryKind==='dialect-area'));
assert.ok(data.features.every(f=>f.properties.entryKind!=='unclassified-area'||f.properties.family==='Unclassifiable'));
assert.equal(data.features.find(f=>f.properties.languageId==='jiri1239').properties.nameZh,'蒙古语（科尔沁）');
assert.equal(data.features.find(f=>f.properties.languageId==='taih1244').properties.nameZh,'吴语（太湖片）');
assert.ok(data.features.find(f=>f.properties.languageId==='taih1244').properties.dialectResidualGeometry.coordinates.length>0,'Taihu extends beyond parent area and must retain visible residual polygons');
const taihuLabel=structuredClone(data.features.find(f=>f.properties.languageId==='taih1244'));
EthnicRegions.labelProperties(taihuLabel);assert.equal(taihuLabel.properties.labelMinZoom,6,'Large dialect labels should appear at regional zoom');
const clip=require('polygon-clipping');
const residualOverlap=clip.intersection(data.features.find(f=>f.properties.languageId==='russ1263').properties.overlapResidualGeometry.coordinates,data.features.find(f=>f.properties.languageId==='even1259').geometry.coordinates);
const residualArea=residualOverlap.reduce((sum,p)=>sum+Math.abs(p[0].reduce((a,v,i,r)=>{const w=r[(i+1)%r.length];return a+v[0]*w[1]-w[0]*v[1]},0)/2),0);
assert.ok(residualArea<1e-7,'Russian/Evenki residual should only share numerical boundary slivers');
const find = name => data.features.find(f => f.properties.group_ === name);
assert.equal(find('Mandarin Chinese').properties.nameZh, '官话');
assert.equal(find('Hindi').properties.nameZh, '印地语');
assert.equal(find('Min Bei Chinese').properties.nameZh, '闽北语');
assert.equal(find('Axi Yi').properties.nameZh, '阿细语');
assert.equal(find('Azhe').properties.nameZh, '阿哲语');
assert.equal(find('Mongghul').properties.nameZh, '土族语（互助）');
assert.equal(find('Mangghuer').properties.nameZh, '土族语（民和）');
assert.notEqual(find('Mongghul').properties.languageId,find('Mangghuer').properties.languageId);
assert.equal(find('Dafla').properties.nameZhKind, 'transliteration');
assert.ok(find('Dafla').properties.nameZhNote.includes('旧分类'));
assert.equal(find('German').properties.familyZh, '印欧语系');
assert.equal(EthnicRegions.color(find('Hindi').properties), EthnicRegions.color({...find('Hindi').properties, gwgroupid:999}));
const elements = new Map();
global.document = {querySelector: id => {
  if (!elements.has(id)) elements.set(id, {hidden:false, addEventListener(event, callback) {this[event]=callback;}, removeAttribute() {}, setAttribute() {}});
  return elements.get(id);
}};
let state = {mapOverlays:{ethnicRegionsSource:'language', ethnicRegions:true, ethnicRegionsOpacity:45}};
let language='zh', saved=0;
EthnicRegions.init({state:()=>state,language:()=>language,save:()=>saved++,render(){},front(){}});
let fetches=0;
global.fetch = async url => {
  fetches++;
  assert.equal(url, 'data/language-areas.geojson?v=17');
  return {ok:true,json:async()=>({type:'FeatureCollection',features:[structuredClone(find('Hindi')), {...structuredClone(find('Hindi')),properties:{...find('Hindi').properties,languageId:'test-family',entryKind:'family-area',nameZh:'印欧语系范围'}}]})};
};
const sources=new Map(), layers=new Map();
const map={getSource:id=>sources.get(id),getLayer:id=>layers.get(id),getStyle:()=>({layers:[]}),
  addSource:(id,s)=>sources.set(id,{...s,setData(data){this.data=data;}}),addLayer:l=>layers.set(l.id,l),removeLayer:id=>layers.delete(id),removeSource:id=>sources.delete(id),
  setLayoutProperty:(id,key,value)=>{const l=layers.get(id);l.layout??={};l.layout[key]=value;},setPaintProperty(){},queryRenderedFeatures:()=>sources.get('ethnic-regions').data.features};
let popupHtml='';
global.maplibregl={Popup:class {setLngLat(){return this;}setHTML(html){popupHtml=html;return this;}addTo(){return this;}on(){}remove(){}}};
(async()=>{
  await EthnicRegions.sync(map);
  assert.equal(elements.get('#ethnicRegionsSource').value,'language');
  assert.ok(Array.isArray(layers.get('ethnic-regions-line').paint['line-opacity']));
  assert.equal(layers.get('ethnic-regions-fill').paint['fill-antialias'],true);
  assert.equal(sources.get('ethnic-regions').data.features.length,1, 'Family aggregate must not duplicate specific areas');
  assert.ok(sources.get('ethnic-regions-labels').data.features.every(f=>!f.properties.labelZh.includes('语系范围')));
  assert.ok(elements.get('#ethnicRegionsNote').textContent.includes('2007'));
  assert.equal(sources.get('ethnic-regions-labels').data.features[0].properties.labelZh,'印地语');
  EthnicRegions.click(map,{point:{},lngLat:{}});
  assert.ok(popupHtml.includes('印地语'));
  language='en';EthnicRegions.refreshLanguage();
  assert.ok(popupHtml.includes('Hindi'));
  assert.deepEqual(layers.get('ethnic-regions-label-0').layout['text-field'],['get','labelEn']);
  const familyLegend=EthnicRegions.legendGroups(data,'affinity');
  const languageLegend=EthnicRegions.legendGroups(data,'language');
  assert.equal(languageLegend.length,new Set(data.features.map(f=>f.properties.languageId)).size);
  assert.equal(familyLegend.flatMap(g=>g.members).length,languageLegend.length);
  assert.equal(familyLegend.find(g=>g.key==='Sino-Tibetan').members.find(m=>m.id==='mand1415').color,EthnicRegions.color(find('Mandarin Chinese').properties,'affinity'));
  assert.ok(elements.get('#languageLegendLink').textContent.includes('View detailed'));
  console.log('Complete legend:',familyLegend.length,'families/categories;',languageLegend.length,'languages');
  assert.ok(elements.get('#languageFamilyLegend').innerHTML.includes('Indo-European'));
  assert.ok(!elements.get('#languageFamilyLegend').innerHTML.includes('data-language-family="Japonic"'));
  assert.ok(!elements.get('#languageFamilyLegend').innerHTML.includes('data-language-family="Koreanic"'));
  const affinityColor=sources.get('ethnic-regions').data.features[0].properties.color;
  assert.equal(elements.get('#languageColorMode').value,'affinity');
  elements.get('#languageColorMode').change({target:{value:'language'}});
  await EthnicRegions.sync(map);
  assert.equal(state.mapOverlays.languageColorMode,'language');
  assert.notEqual(sources.get('ethnic-regions').data.features[0].properties.color,affinityColor);
  elements.get('#languageColorMode').change({target:{value:'affinity'}});
  await EthnicRegions.sync(map);
  assert.equal(sources.get('ethnic-regions').data.features[0].properties.color,affinityColor);
  assert.equal(EthnicRegions.color({dataset:'language',languageId:'unknown',family:''},'affinity'),'hsl(210, 12%, 55%)');
  assert.equal(EthnicRegions.color({dataset:'language',family:'Pama-Nyungan',languageId:'a'},'affinity'),EthnicRegions.color({dataset:'language',family:'Nuclear Trans New Guinea',languageId:'b'},'affinity'));
  const lightness=p=>parseFloat(EthnicRegions.color(p,'affinity').split(',')[2]);
  assert.ok(lightness(find('English').properties)<lightness(find('French').properties));
  assert.ok(lightness(find('Mandarin Chinese').properties)<lightness(find('Tibetan').properties));
  const turkic=data.features.filter(f=>f.properties.family==='Turkic').map(f=>lightness(f.properties));
  assert.ok(Math.max(...turkic)-Math.min(...turkic)<=16);
  assert.equal(EthnicRegions.color(find('Japanese').properties,'affinity'),'hsl(210, 12%, 55%)');
  assert.equal(EthnicRegions.color(find('Korean').properties,'affinity'),'hsl(210, 12%, 55%)');
  const mandarin=find('Mandarin Chinese'),wu=find('Wu Chinese');
  assert.equal(mandarin.properties.kinPath[0],wu.properties.kinPath[0]);
  const hue=f=>parseFloat(EthnicRegions.color(f.properties,'affinity').slice(4));
  assert.equal(hue(mandarin),hue(wu));
  const sino=data.features.filter(f=>f.properties.family==='Sino-Tibetan');
  const colors=sino.map(f=>EthnicRegions.color(f.properties,'affinity'));
  assert.equal(new Set(colors.map(c=>c.split(',')[0])).size,1);
  assert.ok(new Set(colors).size>=4);
  assert.ok(!elements.get('#languageFamilyLegend').innerHTML.includes('Pama-Nyungan'));
  assert.ok(Math.abs(hue(mandarin)-hue(find('German')))>40);
  elements.get('#ethnicRegionsSource').change({target:{value:'greg'}});
  assert.equal(state.mapOverlays.ethnicRegionsSource,'greg');assert.equal(saved,3);
  state.mapOverlays.ethnicRegionsSource='language';
  elements.get('#languageFamilyLegend').change({target:{dataset:{languageFamily:'Indo-European'},checked:false}});
  await EthnicRegions.sync(map);
  assert.equal(sources.get('ethnic-regions').data.features.length,0);
  assert.equal(sources.get('ethnic-regions-labels').data.features.length,0);
  assert.equal(elements.get('#languageFamilyAll').indeterminate,true);
  elements.get('#languageFamilyAll').change({target:{checked:false}});await EthnicRegions.sync(map);
  assert.equal(elements.get('#languageFamilyAll').indeterminate,false);
  elements.get('#languageFamilyAll').change({target:{checked:true}});await EthnicRegions.sync(map);
  assert.equal(sources.get('ethnic-regions').data.features.length,1);
  assert.equal(elements.get('#languageFamilyAll').checked,true);
  assert.equal(fetches,1);
  console.log('PASS: language data, Chinese names, colors, source selection, labels and bilingual popup');
})().catch(error=>{console.error(error);process.exitCode=1;});
