const assert = require('node:assert/strict');
const fs = require('node:fs');
const api = require('../volcano-catalog.js');
assert.equal(new Set(Object.values(api.colors)).size, 9);
for (const [type, group] of [['Stratovolcano', 'strato'], ['Shield', 'shield'], ['Caldera', 'caldera'], ['Volcanic field', 'field'], ['Lava dome', 'dome'], ['Cinder cone', 'cone'], ['Maar', 'maar'], ['Fissure vent', 'fissure'], ['Unknown', 'other']]) {
  assert.equal(api.typeGroup({ primaryType: type }), group);
  assert.match(api.colors[group], /^#[0-9a-f]{6}$/i);
}
const html = fs.readFileSync(require.resolve('../index.html'), 'utf8');
assert.match(html, /id="volcanoLegendTypes"/);
assert.doesNotMatch(html, /id="volcano(?:Type|Eruption)Filter"/);
const data = require('../data/global-volcanoes.json');
assert.equal(api.eruptionYear('8300 BCE'), -8300);
assert.equal(api.eruptionYear('1900 CE'), 1900);
assert.equal(api.eruptionYear('Unknown'), null);
assert.equal(api.eruptionYear(''), null);
const item = { epoch: 'Holocene', primaryType: 'Stratovolcano(es)', lastEruption: '1899 CE' };
assert.equal(api.matches(item, { includeHolocene: false, includePleistocene: true }), false);
assert.equal(api.matches(item, {}), true);
assert.equal(api.matches({ ...item, epoch: 'Pleistocene' }, { includeHolocene: false, includePleistocene: true }), true);
assert.equal(api.matches(item, { type: 'strato', eruption: 'before1900' }), true);
assert.equal(api.matches(item, { eruption: 'since1900' }), false);
assert.equal(api.matches({ ...item, lastEruption: '' }, { eruption: 'before1900' }), false);
assert.equal(api.matches({ ...item, lastEruption: '' }, { eruption: 'unknown' }), true);
assert.equal(api.matches({ ...item, epoch: 'Pleistocene' }, { includePleistocene: false }), false);
assert.equal(api.matches({ ...item, epoch: 'Pleistocene' }, { includePleistocene: true }), true);
const local = [{ volcanoLocationId: 210010, name: 'old', epoch: 'Holocene', rockType: 'retained rock' }, { volcanoLocationId: 210020, epoch: 'Holocene' }, { volcanoLocationId: 210030, epoch: 'Pleistocene' }];
const merged = api.merge(local, [{ Volcano_Number: 210010, Volcano_Name: 'new', Latitude: 1, Longitude: 2, Elevation__m_: -200 }]);
assert.equal(merged.items.length, 3);
assert.equal(merged.items[0].name, 'new');
assert.equal(merged.items[0].rockType, 'retained rock');
assert.equal(merged.items[0].elevation, -200);
assert.equal(merged.items[2].epoch, 'Pleistocene');
assert.equal(merged.retainedOnly, 1);
assert.equal(data.items.length, 2665);
assert.equal(data.items.filter(x => x.epoch === 'Pleistocene').length, 1376);
assert.equal(data.reference.comparison.retainedOnly, 8);
assert.equal(data.reference.comparison.updated, 1281);
const app = fs.readFileSync(require.resolve('../app.js'), 'utf8');
const css = fs.readFileSync(require.resolve('../styles.css'), 'utf8');
assert.match(app, /mousemove", "volcano-points"/);
assert.match(app, /volcanoPopupContent\(props, true\)/);
assert.match(app, /volcano\.si\.edu\/volcano\.cfm\?vn=/);
assert.match(css, /#volcanoLegend\s*\{\s*pointer-events:\s*auto/);
console.log('PASS: volcano reference merge, retained coverage, unknown dates, type/period filters, hover and GVP links');
